id = "your-name-theme"
name = "Your Name. Theme"
version = "1.1.0"
schema_version = 1
authors = ["Ahum Maitra <theahummaitra@gmail.com>"]
description = "This theme is inspired to Your Name. anime film. Thanks!"
repository = "https://github.com/TheAhumMaitra/Your-Name-Zed-theme"
